baseURL = 'https://ваш-логин.github.io/детские-книги/'
languageCode = 'ru'
title = 'Детские аудиокниги с QR'

theme = 'ananke'

[params]
  favicon = ''
  site_logo = ''
  description = "Аудиокниги для детей на казахском и английском"

[languages]
  [languages.kz]
    title = 'Балалар кітаптары'
    weight = 1
  [languages.en]
    title = 'Children\'s Books'
    weight = 2

defaultContentLanguage = 'kz'
