baseURL = 'https://alternativeig.github.io/child-books/'
languageCode = 'ru'
title = 'Детские аудиокниги с QR'

# ВАЖНО: подключаем тему
theme = 'ananke'

[params]
  favicon = ""
  description = "Аудиокниги для детей с QR-кодами"
  read_more_copy = "Читать дальше"

[languages]
  [languages.kz]
    title = 'Балалар кітаптары'
    weight = 1
  [languages.en]
    title = 'Children\'s Books'
    weight = 2

defaultContentLanguage = 'kz'

# Отключаем лишнее
disableKinds = ["taxonomy", "taxonomyTerm"]
